spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: 1314

mybatis:
  config-locations: classpath:/com.example.test.mapper/*Mapper.xml
  type-aliases-package: com.example.test.domain

